In [1]:
x = 3

In [2]:
x

3

In [3]:
type(x)

int

----

---

In [4]:
q1 = true

NameError: name 'true' is not defined

In [1]:
q1 = True
type(q1)

bool

In [6]:
q1

True

----

In [3]:
FirstName = "Nouman"
LastName = 'Rasheed'

In [4]:
FirstName + LastName
type(FirstName)

str

In [13]:
print(FirstName, LastName)

Nouman Rasheed


----

In [14]:
5>1

True

In [15]:
not(5>1)

False

In [16]:
result = 5>1
result2 = not(5>1)

In [17]:
result or result2

True

In [18]:
result and result2

False

---

In [19]:
# while loop

In [20]:
check = 0
while check < 12:
    print(check)
    check = check + 1
print("end of while loop") # loop body is detected by indentation

0
1
2
3
4
5
6
7
8
9
10
11
end of while loop


-------

In [1]:
# if, nested if and chained

In [3]:
import numpy as np
from numpy.random import randn

In [3]:
randn()

0.11583260368705153

In [25]:
#Nested if
x = randn()
if x>1:
    answer = "Greater than 1"
else:
    if x<-1:
        answer = "Less than -1"
    else:
        answer = "Between 1 and -1"
print(x)
print(answer)

0.960158583257
Between 1 and -1


In [4]:
#chained statements
x = randn()
if x>1:
    answer = "Greater than 1"
elif x<-1:
    answer = "Less than -1"
else:
    answer = "Between 1 and -1"
print(x)
print(answer)

-0.8109031750983837
Between 1 and -1


-----------------------

In [5]:
#Lists

In [6]:
range(5)

range(0, 5)

In [7]:
list(range(5
          ))

[0, 1, 2, 3, 4]

In [9]:
x = list(range(1,10,1))
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
x[0]

1

In [11]:
x[-1]

9

In [13]:
len(x) # length of the list

9

In [15]:
x[2:6]

[3, 4, 5, 6]

In [24]:
x[-7:6] #negative and postive index work together

[3, 4, 5, 6]

In [26]:
x[-7:-3] #negative indexes

[3, 4, 5, 6]

In [27]:
x[2:7:2] #second colon is step size

[3, 5, 7]

In [28]:
x[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
x[::3]

[1, 4, 7]

In [31]:
x[::-1] # negative step to go backward

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [34]:
x[2:6:-1] # empty since starting at 2 we can only go back a step -1. 


[]

In [35]:
x[6:2:-1]

[7, 6, 5, 4]

In [36]:
# Tuples is immutable list: list that can not be changed. Instead of square brackets using normal parenthesis

In [37]:
t1 = (350, 30, 12)

In [39]:
t1[0]

350

In [40]:
t1[0] = 24

TypeError: 'tuple' object does not support item assignment

In [44]:
print(max(t1))
print(min(t1))

350
12


--------------------

In [66]:
import numpy as np

In [46]:
l1 = [123, 123145, 5, -2432, -243]

In [47]:
np.array(l1)

array([   123, 123145,      5,  -2432,   -243])

In [48]:
a = np.array(l1)

In [50]:
type(a)

numpy.ndarray

In [51]:
a.mean()

24119.6

In [53]:
a[:]

array([   123, 123145,      5,  -2432,   -243])

In [61]:
b = a[2:4] # b is not a new array its just a truncated view of original array a

In [62]:
b[:] = 111

In [63]:
b

array([111, 111])

In [64]:
a # value of array a is changed for 2 and 3rd element

array([   123, 123145,    111,    111,   -243])

In [15]:
xx = list(range(10))

In [3]:
Month_Revenue= [415,652,753,423,5632,623,76,48,769,3210,3511,412]

In [13]:
#Dictionary setup to help index through some other array, matrix or list
dict1 = {'Jan':0, 'Feb':1, 'Feb':2, 'Apr':3, 'May':4, 'Jun':5, 'Jul':6, 'Aug':7, 'Sep':8, 'Oct':9, 'Nov':10, 'Dec':11}

In [15]:
Month_Revenue[dict1["Aug"]]

48

In [1]:
import numpy as np

In [34]:
a = np.random.rand(3,2) # generates random matrix

In [35]:
a.shape # Returns size of the matrix

(3, 2)

In [5]:
Revenue_Array = np.array(Month_Revenue)

In [12]:
Rand = list(range(30))

In [24]:
# Reshape List into an Matrix
C = np.reshape(Rand,(3,10)) # C++ like where rows are populated first - default 
# same as C = np.reshape(Rand,(3,10), 'C')
F = np.reshape(Rand,(3,10), 'F') # Fortran like where rows are populated first 

In [30]:
print('C')
print(C)
print('F ')
print(F)

C
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
F 
[[ 0  3  6  9 12 15 18 21 24 27]
 [ 1  4  7 10 13 16 19 22 25 28]
 [ 2  5  8 11 14 17 20 23 26 29]]


In [33]:
import numpy as np
v1 = [1, 22, 33]
v2 = ["Hi", "there", "friend"]
v3 = [11, 3, 2016]
D  = np.array([v1,v2,v3])
D[2,1]
print(D)

[['1' '22' '33']
 ['Hi' 'there' 'friend']
 ['11' '3' '2016']]
